### ISSUE TITLE
How to access a folder which is out side of the webfolder

### ISSUE THREAD

**Issue by yashnishad** [manishma/IZWebFileManager#2]
Hi ,   

   By this application i want  that every user has his own folder  and can access only his folder . I have done it But Issue  is this , I want that  root folder will keep outside the web folder and i give outsider folder Path as the root folder . which have physically in other drive
   Please solve this problem .

Thanks in avance

(Yash)

**Comment by manishma** [comment]
Hi,

ZWebFileManager browse only directories within application from security reason.

To make it browse a directory from outside of application, you have to map it as virtual folder into application and then access it as regular one.

Please, take a look for similar problems, that have been solved in this way:
https://groups.google.com/forum/?fromgroups=#!searchin/izwebfilemanager/virtual$20directory

**Comment by yashnishad** [comment]
Thanks , To your reply manishma ji, 

```
             I tried By UNC Path but it want whole website path and i want that my file manger folder is in different location and website folder in different   . 

          Will you give me an example  to map  virtual folder , actually i tried it but not succeed because i am novice user . if you give me an example or steps, or any link which help me than i am very grateful to you. 
```

**Comment by manishma** [comment]
Take a look  

http://support.microsoft.com/kb/172138

http://www.microsoft.com/technet/prodtechnol/WindowsServer2003/Library/IIS/5adfcce1-030d-45b8-997c-bdbfa08ea459.mspx?mfr=true

http://msdn.microsoft.com/en-us/library/bb763173(v=vs.100).aspx

Igor Zelmanovich

**Comment by yashnishad** [comment]
Thanks,
      , Damn yar how can i missed it I got It,and also rectify the problem  Really very very thanks to you .....  please give me one more favor that Tell Me how to pass session in different  virtual directory. or is it possible ? actually i make this application for  private folder thats why i need to pass session of userid is iot possible or another method  to do it Plz ........... tell me..................................................!

**Comment by manishma** [comment]
If I understand you, you need different folders for each user. 

You can achieve this in such way:
1. create a virtual directory where you will create user's folders 
2. create folder for each user in this directory (you may create folder on demand)
3. set rood directory of IZWebFileManager to point to user's folder on page load.

**Comment by yashnishad** [comment]
Thanks to your Support ,

 I did it ,

   Thank you very Much manishma
