### ISSUE TITLE
How to share  a Private folder file to another user

### ISSUE THREAD

**Issue by yashnishad** [manishma/IZWebFileManager#3]
Hi, Manishma, 

First of all i want to say thanks to your  help and quick response . 

```
As i told earlier that i create this application to private folder  of the user . and i want to added that if user want to share any file to another user (whose id he knows) than what t will the process i can do programmed it. 
```

**Comment by manishma** [comment]
For each user you can add more then one root directory. If user has a shared folder, you may mount it for each of users who may access it in additional to private folder.

**Comment by yashnishad** [comment]
yes i did it,

```
but the problem is this , if a user want to transfer a file to another user , than its want to move that private folder ,
```

  but as my experience , this s/w denies it bcz of security . there is any solution to transfer a file to another user .

 If there is any demo, then plz................

(How can i Get the  source file location path  to copy  another user folder) for transfer file
 thanks
