### ISSUE TITLE
Error i to uploading winrar  and large  size of file 

### ISSUE THREAD

**Issue by yashnishad** [manishma/IZWebFileManager#4]
hi manishma when the user trying to upload a winrar file  or big size file then their is an error occure ..

Maximum request length exceeded.

Exception Details: System.Web.HttpException: Maximum request length exceeded.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[HttpException (0x80004005): Maximum request length exceeded.]
   System.Web.HttpRequest.GetEntireRawContent() +8763266
   System.Web.HttpRequest.GetMultipartContent() +62
   System.Web.HttpRequest.FillInFormCollection() +168
   System.Web.HttpRequest.get_Form() +68
   System.Web.HttpRequest.get_HasForm() +8718647
   System.Web.UI.Page.GetCollectionBasedOnMethod(Boolean dontReturnNull) +97
   System.Web.UI.Page.DeterminePostBackMode() +63
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +133

their is any solution ...
thanks

**Comment by manishma** [comment]
This is configuration of ASP.NET
You can change it in Web.config in httpRuntime section http://msdn.microsoft.com/en-us/library/e1f13641(v=vs.71).aspx

See maxRequestLength attrubute

**Comment by yashnishad** [comment]
thanks to reply , i have sort out to max size prblm but its also through the exception when i try to upload a winrar File .
There is any solution for that

**Comment by manishma** [comment]
Do you get an exception? Send exception details.

**Comment by yashnishad** [comment]
thanx manishama i am heartly oblized to sort out my problems. I got the problem and fixed it.

thank you very much dear.
